# Generated by Django 4.1.7 on 2023-08-10 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LinkedInPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(max_length=200, unique=True)),
                ('captions', models.TextField(blank=True, null=True)),
                ('reactions', models.IntegerField(blank=True, default=0, null=True)),
                ('post_date_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField()),
                ('social_media', models.CharField(choices=[('Instagram', 'Instagram'), ('Facebook', 'Facebook'), ('Linkedin', 'Linkedin'), ('Tiktok', 'Tiktok'), ('Twitter', 'Twitter'), ('YouTube', 'YouTube')], max_length=20)),
                ('ue1', models.CharField(choices=[('Kemenkeu', 'Kemenkeu'), ('Setjen', 'Setjen'), ('DJA', 'DJA'), ('DJP', 'DJP'), ('DJPPR', 'DJPPR'), ('DJPB', 'DJPB'), ('DJKN', 'DJKN'), ('DJBK', 'DJBK'), ('Itjen', 'Itjen'), ('DJBC', 'DJBC'), ('BKF', 'BKF'), ('BPPK', 'BPPK'), ('SMV', 'SMV')], max_length=50)),
                ('posts', models.IntegerField(blank=True, null=True)),
                ('followers', models.IntegerField(blank=True, null=True)),
                ('post_urls', models.TextField(blank=True, null=True)),
                ('captions', models.TextField(blank=True, null=True)),
                ('viewers', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('likes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
