# Generated by Django 4.1.7 on 2023-08-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediadata',
            name='similarity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
