# Generated by Django 4.1.7 on 2023-08-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0002_socialmediadata_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediadata',
            name='verify',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
