# Generated by Django 4.1.7 on 2023-08-17 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0003_socialmediadata_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediadata',
            name='verify',
            field=models.BooleanField(default=False),
        ),
    ]
