# Generated by Django 4.1.7 on 2023-08-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socmed_data', '0004_alter_socialmediadata_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediadata',
            name='status_similarity',
            field=models.TextField(blank=True, null=True),
        ),
    ]
