# Generated by Django 4.1.7 on 2023-08-10 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InputAgendaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_agenda', models.IntegerField()),
                ('topik_agenda', models.CharField(max_length=200)),
                ('pesan_kunci', models.TextField()),
                ('sub_pesan_kunci', models.TextField()),
                ('agenda_date_time_start', models.DateTimeField(default=django.utils.timezone.now)),
                ('agenda_date_time_end', models.DateTimeField()),
            ],
        ),
    ]
